version: '3.8'

services:
  video-anomaly-detector:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2024-02-15-preview}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME:-gpt-4-vision-preview}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - UPLOAD_FOLDER=uploads
      - MAX_CONTENT_LENGTH=52428800  # 50MB
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app:ro  # Mount for development (read-only)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production-like setup
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - video-anomaly-detector
    restart: unless-stopped
    profiles:
      - production